"""'followers'

Revision ID: 251e4854ef4c
Revises: 99a18f68c13a
Create Date: 2019-04-29 16:38:02.933804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251e4854ef4c'
down_revision = '99a18f68c13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
